version: '3.7'

services:
  postgres:
    container_name: database
    image: postgres:13.2-alpine
    hostname: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpasswd}
      POSTGRES_DB: assembleia-db
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  java-app:
    depends_on:
      - postgres
    container_name: java-app
    image: java-app
    environment:
      POSTGRES_URL: jdbc:postgresql://database:5432/
    ports:
      - "${JAVA_APP_PORT:-8080}:8080"
    networks:
      - postgres
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
